apiVersion: v1
kind: Pod
metadata:
  name: mypod-with-secret-env
spec:
  containers:
  - name: mypod-with-secret-env
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password      
  restartPolicy: Never
